### ISSUE TITLE
Version 1.3 is missing in Maven Central

### ISSUE THREAD

**Issue by marksto** [dernasherbrezon/mockfs#1]
Hi Andrew and thank you for a great Open Source stuff — this library is neat!

Unfortunately, I must warn you that after the recent changes that you added to the `master` branch a few days ago, we now miss the version `1.3` artifact in the Maven Central repository.

Here's what I get when run Maven locally:
`Could not find artifact com.aerse:mockfs:pom:1.3 in central (https://repo.maven.apache.org/maven2)`

However, version `1.4` is found and pulled normally.

Cheers,
Mark

**Comment by dernasherbrezon** [comment]
Hi!

Yes, 1.3 failed to build due to 502 status code from nexus. I just incremented version by 1 and built one more time.
